type JobDetail {
  relatedPosting: JobPosting
  positionNeeded: String!
  amountNeeded: Int!
}

type JobContact {
   lat: Float!
   lon: Float!
   address: String!
   institution: String!
}

type JobPosting {
    title: String!
    jobOwner: User!
    description: String!
    jobContact: JobContact!
    jobDetails: [JobDetail]! @relation
    applicants: [JobApplication] @relation
}

enum USER_TYPE {
    HELPER
    FARMER
}

type User {
    auth0Id: String!
    userType: USER_TYPE!
    firstName: String!
    lastName: String!
    email: String!
    phone: String!
    ownedJobPostings: [JobPosting] @relation
    ownedJobApplications: [JobApplication] @relation
}

enum APPLICATION_STATUS {
    APPLIED
    DECLINED
    ACCEPTED
}

type JobApplication {
    jobPosting: JobPosting!
    status: APPLICATION_STATUS!
    position: String!
    info: String!
    applicant: User!
}


type Query {
   viewer: User
   currentUser(auth0Id: String!): User @index(name: "userByAuth0Id")
   jobs: [JobPosting]
}
